---
name: ci
on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  gogenerate:
    name: Check generated files
    uses: networkservicemesh/.github/.github/workflows/cmd-gogenerate.yaml@main
